name: Deploy Artifacts
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install xpath
        run: sudo apt install -y libxml-xpath-perl
      - name: Install deps
        run: mvnrepo/mvninstall.sh --clean $(xpath -q -e '/project/version/text()' pom.xml)
      - name: Deploy package
        run: mvn --batch-mode -DskipITs -Dbuildsupport-staging.skip=true clean deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.actor }}
