name: Publish package to GitHub Packages
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install xpath
        run: sudo apt install -y libxml-xpath-perl
      - name: Install deps
        run: mvnrepo/mvninstall.sh --clean $(xpath -q -e '/project/parent/version/text()' pom.xml)
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
